### ISSUE TITLE
bug: 从6.x 升级到 7.x后一直报错，找不到问题所在

### ISSUE THREAD

**Issue by tench** [dotnetcore/BootstrapBlazor#1031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

可以在运行中看到的错误是这个：
 The requested module './index.js' does not provide an export named 'getElementById'

**Comment by ArgoZhang** [comment]
@tench 提供复现用例啊，你这样问怎么帮你？

**Comment by tench** [comment]
> @tench 提供复现用例啊，你这样问怎么帮你？顺便帮忙点个 star 哈哈

我找到问题了，是那些js文件的问题，如果发布后是没问题的，就是用vs调试时，加载js失败。点发布后 _content  @里的js没有问题，找不到怎么清除调试时的缓存的办法。。。。
:1  [2023-04-18T07:18:12.524Z] Error: Microsoft.JSInterop.JSException: The requested module './index.js' does not provide an export named 'getElementById'
SyntaxError: The requested module './index.js' does not provide an export named 'getElementById'
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at BootstrapBlazor.Components.JSModuleExtensions.LoadModule(IJSRuntime jsRuntime, String fileName, Boolean relative)
   at BootstrapBlazor.Components.BootstrapModuleComponentBase.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
log @ blazor.server.js:1

**Comment by densen2014** [comment]
浏览器 F12 强刷

**Comment by ArgoZhang** [comment]
@tench 浏览器隐私模式

**Comment by tench** [comment]
好了，谢谢大佬解答，原来问题如此简单.......
