### ISSUE TITLE
bug:  JSDisconnectedException at BootstrapBlazor.Components.Chart.DisposeAsync()

### ISSUE THREAD

**Issue by bigsinger** [dotnetcore/BootstrapBlazor#1108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

在关闭页面的时候，会出现如下的异常信息：
```
Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at BootstrapBlazor.Components.Chart.DisposeAsync(Boolean disposing)
   at BootstrapBlazor.Components.Chart.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
```

### .NET Version

7

**Comment by ArgoZhang** [comment]
@bigsinger 提供一个复现的例子工程，方便我们排查问题

**Comment by bigsinger** [comment]
> @bigsinger 提供一个复现的例子工程，方便我们排查问题

网上找到这个，不知道有没有关系：
https://gitee.com/LongbowEnterprise/BootstrapBlazor/pulls/1303

**Comment by ArgoZhang** [comment]
未提供复现例子 自动关闭 Issue

**Comment by bigsinger** [comment]
参考 #1016 的做法，重载函数 DisposeAsync 就可以解决，从此世界清净了。给出代码给遇到的朋友参考：
```
namespace BIChart;

/// <summary>
/// 优化：无须为图表控件绑定变量，业务代码更加简洁。在需要重新初始化图表的时候调用 StateHasChanged 即可自动刷新。
/// </summary>
public class MyChart : BootstrapBlazor.Components.Chart {
    bool isUserRender = false;
    protected override async Task OnAfterRenderAsync(bool firstRender) {
        if (isUserRender) {
            await Reload();
            return;
        } else if (!firstRender) {
            isUserRender = true;
        }
        await base.OnAfterRenderAsync(firstRender);
    }

    /// <summary>
    /// 解决异常问题
    /// </summary>
    protected override async ValueTask DisposeAsync(bool disposing) {
        try {
            await base.DisposeAsync(disposing);
        } catch (Exception) {
        }
    }

}

```
