### ISSUE TITLE
bug: 单文件发布出现错误 publish to single file get version incorrect

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/BootstrapBlazor#1328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

发布后进入界面提示错误

```
System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at BootstrapBlazor.Components.DefaultJSVersionService.<GetVersion>g__GetVersionImpl|4_0()
   at BootstrapBlazor.Components.DefaultJSVersionService.GetVersion()
   at BootstrapBlazor.Components.BootstrapModuleComponentBase.OnAfterRenderAsync(Boolean firstRender)
```

![image](https://github.com/dotnetcore/BootstrapBlazor/assets/8428709/7250ebee-e77e-4918-8d8e-ee1a196be216)

### Expected Behavior

System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at BootstrapBlazor.Components.DefaultJSVersionService.<GetVersion>g__GetVersionImpl|4_0()
   at BootstrapBlazor.Components.DefaultJSVersionService.GetVersion()
   at BootstrapBlazor.Components.BootstrapModuleComponentBase.OnAfterRenderAsync(Boolean firstRender)

### .NET Version

7.0

**Comment by densen2014** [comment]
// 发布时选择单文件时 此代码报错
ver = FileVersionInfo.GetVersionInfo(typeof(BootstrapComponentBase).Assembly.Location).ProductVersion;

找到了, mark一下, 关闭重复issue

**Comment by densen2014** [comment]
warning IL3000: 'System.Reflection.Assembly.Location' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'.

**Comment by ArgoZhang** [comment]
@densen2014 

最新代码如下  [Version ??= ConfigVersion ?? GetVersionImpl();](https://github.com/dotnetcore/BootstrapBlazor/blob/525fa0e76ecd3e6096b14a36470224c1f2acdc12/src/BootstrapBlazor/Services/DefaultJSVersionService.cs#L26)

这里优先走 `ConfigVersion`

**Comment by densen2014** [comment]
> @densen2014
> 
> 最新代码如下 [Version ??= ConfigVersion ?? GetVersionImpl();](https://github.com/dotnetcore/BootstrapBlazor/blob/525fa0e76ecd3e6096b14a36470224c1f2acdc12/src/BootstrapBlazor/Services/DefaultJSVersionService.cs#L26)
> 
> 这里优先走 `ConfigVersion` 这个是针对单文件做配置用的
> 
> 如果需要发布单文件，就做如下配置
> 
> ### SSR 模式
> ```
> "BootstrapBlazorOptions": {
>   "JSModuleVersion": "7.6.7"
> }
> ```
> 
> ### WASM 模式
> ```
> builder.Services.AddBootstrapBlazorServices(options =>
> {
>     options.JSModuleVersion = "7.6.7";
> });
> ```

写配置文件我觉得不够优雅. 我先完整测试一下

**Comment by densen2014** [comment]
![image](https://github.com/dotnetcore/BootstrapBlazor/assets/8428709/4bea6434-ec4c-432e-95a1-7c57e1f06338)

选release发布包本地测试, 结果符合预期!

**Comment by densen2014** [comment]
**bb7.7.0**

- [ ] Costura.Fody 单文件  OK

net7依赖框架单文件  OK
net7依赖框架单文件+ReadyRun  OK
