### ISSUE TITLE
bug: IpAddress Component error on startup Microsoft.JSInterop.JSException: Unexpected token '}'

### ISSUE THREAD

**Issue by coddoge** [dotnetcore/BootstrapBlazor#1862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Error on application start, compoent disappear  

### Expected Behavior

I was update package from 7.8.11 to 7.9.1-beta01

Before update, its work properly

### Steps To Reproduce

Cerate a new BlazorWASM application (net7.0)

add package in csproj

    <PackageReference Include="BootstrapBlazor" Version="7.9.1-beta01" />

add services

    builder.Services.AddBootstrapBlazor();

add `BootstrapBlazorRoot` warp on App.razor

append below codes to Index.razor

```
<IpAddress @bind-Value="@_strIP" /> 

@code
{
    private string? _strIP="1.2.3.4";
}

```

### Exceptions (if any)

Console error log:

```
fail: Microsoft.AspNetCore.Components.Web.ErrorBoundary[0]
      Microsoft.JSInterop.JSException: Unexpected token '}'
      SyntaxError: Unexpected token '}'
         at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
         at BootstrapBlazor.Components.JSModuleExtensions.LoadModule(IJSRuntime jsRuntime, String fileName, String version)
         at BootstrapBlazor.Components.BootstrapModuleComponentBase.OnAfterRenderAsync(Boolean firstRender)
         at BootstrapBlazor.Components.ValidateBase`1.<OnAfterRenderAsync>d__65[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
Microsoft.JSInterop.JSException: Unexpected token '}'
SyntaxError: Unexpected token '}'
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at BootstrapBlazor.Components.JSModuleExtensions.LoadModule(IJSRuntime jsRuntime, String fileName, String version)
   at BootstrapBlazor.Components.BootstrapModuleComponentBase.OnAfterRenderAsync(Boolean firstRender)
   at BootstrapBlazor.Components.ValidateBase`1.<OnAfterRenderAsync>d__65[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

### .NET Version

7.0.400-preview.23330.10

**Comment by ArgoZhang** [comment]
@coddoge hi. this is not repro. could you provide a demo project/repo for this?

**Comment by coddoge** [comment]
this is a demo project

https://anonfiles[.]com/bdCaV45fze/BlazorApp1_7z

Please pay attention in BlazorApp1.csproj
```
		<!--<PackageReference Include="BootstrapBlazor" Version="7.8.11" />--> <!--OK-->
		<PackageReference Include="BootstrapBlazor" Version="7.9.1-beta01" />
		<!--<PackageReference Include="BootstrapBlazor" Version="7.9.1-beta02" />--> <!--NG-->
```

**Comment by ArgoZhang** [comment]
@coddoge try `7.9.1-beta02` it's work on my local

**Comment by coddoge** [comment]
@ArgoZhang Sorry for late reply.

Today i can not repro on my computer, but another computer can repo by 7.9.1-beta01, but 7.9.1-beta02 work properly

I tryied to clear browser cache and clean/rebuild on both computer it's still.

I will keep watching and going on 7.9.1-beta02
