### ISSUE TITLE
Table multi-level items bug

### ISSUE THREAD

**Issue by mbonacci** [dotnetcore/BootstrapBlazor#269]
### Describe the bug
Table component breaks when complex object is used as table item. 
When column is bound to a property of sub-item, NullReferenceException is thrown many times.

The workaround is to use a Template for a column, but then sorting and filtering are broken.
Also if I try `<TableColumn Field="context.SubItem?.SubName" />` (without @bind-), then another exception is thrown.

### To Reproduce
```
@page "/test"

<Table TItem="Item" Items="Items">
    <TableColumns>
        <TableColumn @bind-Field="context.Name" />
        <TableColumn @bind-Field="context.SubItem.SubName" />
    </TableColumns>
</Table>

@code {
    List<Item> Items = new() { 
        new() { Name = "Item1", SubItem = new() { SubName = "SubName1" } }
    };

    public class Item
    {
        public string? Name { get; set; }
        public SubItem SubItem { get; set; } = default!;
    }

    public class SubItem {
        public string? SubName { get; set; }
    }
}
```

### Exceptions (if any)
```
fail: Microsoft.AspNetCore.Components.Web.ErrorBoundary[0]
      System.NullReferenceException: Object reference not set to an instance of an object.
         at SilverMonitor.Client.Pages.Admin.Test.<>c__DisplayClass0_0.<BuildRenderTree>b__1(RenderTreeBuilder __builder2)
         at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
         at BootstrapBlazor.Components.Table`1[[SilverMonitor.Client.Pages.Admin.Test.Item, SilverMonitor.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<BuildRenderTree>b__1064_1(RenderTreeBuilder __builder2)
         at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
         at Microsoft.AspNetCore.Components.CascadingValue`1[[BootstrapBlazor.Components.Table`1[[SilverMonitor.Client.Pages.Admin.Test.Item, SilverMonitor.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], BootstrapBlazor, Version=6.11.28.0, Culture=neutral, PublicKeyToken=c20f2177a7066899]].Render(RenderTreeBuilder builder)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

If column is specified without 2-way binding and field is made nullable as `<TableColumn Field="context.SubItem?.SubName" />`, then the exception is:
```
System.InvalidOperationException: 类型 Item 未找到  属性，无法获取其值
   at System.Linq.LambdaExtensions.<GetPropertyValueLambda>g__GetSimplePropertyExpression|34_0[Item,Object](<>c__DisplayClass34_0`2& )
   at System.Linq.LambdaExtensions.GetPropertyValueLambda[Item,Object](Item model, String propertyName)
   at BootstrapBlazor.Components.CacheManager.<>c__DisplayClass30_1`2[[SilverMonitor.Client.Pages.Admin.Test.Item, SilverMonitor.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<GetPropertyValue>b__1(ICacheEntry entry)
   at BootstrapBlazor.Components.CacheManager.<>c__DisplayClass13_0`1[[System.Func`2[[SilverMonitor.Client.Pages.Admin.Test.Item, SilverMonitor.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<GetOrCreate>b__0(ICacheEntry entry)
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[Func`2](IMemoryCache cache, Object key, Func`2 factory)
   at BootstrapBlazor.Components.CacheManager.GetOrCreate[Func`2](Object key, Func`2 factory)
   at BootstrapBlazor.Components.CacheManager.<>c__DisplayClass30_0`2[[SilverMonitor.Client.Pages.Admin.Test.Item, SilverMonitor.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<GetPropertyValue>g__GetValue|0()
   at BootstrapBlazor.Components.CacheManager.GetPropertyValue[Item,Object](Item model, String fieldName)
   at BootstrapBlazor.Components.Utility.GetPropertyValue[Item,Object](Item model, String fieldName)
   at BootstrapBlazor.Components.Table`1[[SilverMonitor.Client.Pages.Admin.Test.Item, SilverMonitor.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetItemValue(String fieldName, Item item)
   at BootstrapBlazor.Components.Table`1.<>c__DisplayClass300_0.<<GetValue>b__0>d[[SilverMonitor.Client.Pages.Admin.Test.Item, SilverMonitor.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.ThreadPool.Callback()
```

### Further technical details
- BootstrapBlazor version: 6.11.28
- The IDE: VS 2022
-.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

**Comment by ArgoZhang** [comment]
@mbonacci you can try the following code

```
public class Item
{
    public string? Name { get; set; }
    public SubItem SubItem { get; set; } = new SubItem();
}
```
