### ISSUE TITLE
bug(TableExport): generate file failed

### ISSUE THREAD

**Issue by james-chao** [dotnetcore/BootstrapBlazor#3301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

升級BB 8.4.7 and TableExport 8.0.6 後，原先的EXCEL 匯出就發生錯誤(錯誤訊息如下)，原先的BB8.4.6 and and TableExport 8.0.5 是正常可匯出 EXCEL File的，請問Cannot resolve scoped service 'BootstrapBlazor.Components.DownloadService' from root provider. 是甚麼意思?
錯誤訊息:
VSIDE: Microsoft Visual Studio Enterprise 2022 17.0
Message: Cannot resolve scoped service 'BootstrapBlazor.Components.DownloadService' from root provider.
*********************************************
StackTrace: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(ServiceCallSite callSite, IServiceScope scope, IServiceScope rootScope)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
at BootstrapBlazor.Components.DefaultTableExport.InternalExportAsync[TModel](IEnumerable`1 items, IEnumerable`1 cols, ExcelType excelType, String fileName, TableExportOptions options)
at BootstrapBlazorCRD.Shared.Pages.CCSettingTable.UserLevelPage.OnExportAsync(ITableExportDataContext`1 context) in C:\Users\92070119\source\repos\BootstrapBlazorCRD\BootstrapBlazorCRD\BootstrapBlazorCRD.Shared\Pages\CCSettingTable\UserLevelPage.razor:line 146
at BootstrapBlazor.Components.Table`1.ExecuteExportAsync(Func`1 callback)
at BootstrapBlazor.Components.BootstrapComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)

### Expected Behavior

導出EXCEL 用
    private async Task<bool> OnExportAsync(ITableExportDataContext<Users> context)
    {
        var ret = false;
        ret = await ExcelExport!.ExportExcelAsync(Items!, context.Columns);
        return ret;
    }

### .NET Version

8.0.204

**Comment by ArgoZhang** [comment]
请提供复现工程，所有的问题不要自己描述，一律提供复现工程

**Comment by james-chao** [comment]
@ArgoZhang 重新Update new packages 就好了，目前BB 8.4.7 and TableExport 8.0.7 是OK 的，感謝!
