### ISSUE TITLE
bug(PdfReader): Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]

### ISSUE THREAD

**Issue by yasz** [dotnetcore/BootstrapBlazor#3305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when use pdf viewer in blazorserver  prompt  warning...
but blazorwasm mode does not prompt.
```
C:\Users\mini>dotnet --version
8.0.204
dotnet new blazorserver -o .
```

### Expected Behavior

no warning like blazorwasm

### Steps To Reproduce

dotnet run

### Exceptions (if any)

```
<PackageReference Include="BootstrapBlazor.PdfReader" Version="8.0.3" />

<PdfReader Height="400px"
    FileName="http://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf"
    Navpanes="false" Toolbar="false" Statusbar="false" Pagemode="EnumPageMode.None" Zoom="EnumZoomMode.Auto" />


warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.JSInterop.Implementation.JSObjectReference.DisposeAsync()
         at BootstrapBlazor.Components.PdfReader.DisposeAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'T9ojWsgiYE3zPPCqlai_CLg9JPd7FzBUUalrVXN2AQ4'.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.JSInterop.Implementation.JSObjectReference.DisposeAsync()
         at BootstrapBlazor.Components.PdfReader.DisposeAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
```

### .NET Version

8.0.204

**Comment by ArgoZhang** [comment]
@yasz sure. will bump a new version after fixing this issue. could you give this project a star? thanks

**Comment by ArgoZhang** [comment]
@yasz Hi this issue is not repro

<img width="1505" alt="image" src="https://github.com/dotnetcore/BootstrapBlazor/assets/22001478/64ecd298-12cc-445d-9af9-4a5f50d034ef">

could you provider a mini repro-project

**Comment by yasz** [comment]
> <PdfReader Height="400px"
>     FileName="http://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf"
>     Navpanes="false" Toolbar="false" Statusbar="false" Pagemode="EnumPageMode.None" Zoom="EnumZoomMode.Auto" />

try refresh ~
[demo.zip](https://github.com/dotnetcore/BootstrapBlazor/files/15021580/demo.zip)
