### ISSUE TITLE
验证表单验证后再输入报错：TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by LeiLei-Liu** [dotnetcore/BootstrapBlazor#4694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

验证表单中的输入框，不填写内容，点击提交，触发验证，后再次输入，当失去焦点后，报错：TypeError: Cannot convert undefined or null to object。

bootstrap.blazor.bundle.min.js:6 
 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at cs._isWithActiveTrigger (bootstrap.blazor.bundle.min.js:6:68800)
    at bootstrap.blazor.bundle.min.js:6:64799
    at g (bootstrap.blazor.bundle.min.js:6:2108)
    at HTMLDivElement.a (bootstrap.blazor.bundle.min.js:6:2486)
    at s (bootstrap.blazor.bundle.min.js:6:722)
    at bootstrap.blazor.bundle.min.js:6:2537

### Expected Behavior

修复Bug

### Interactive render mode

Interactive Auto (Server, then client)

### Steps To Reproduce

复现工程见附件，步骤如下：
1. 点击Counter，后点击页面中的提交按钮；
2. 2个输入框触发验证后，在任一输入框中输入内容；
3. 当输入框失去焦点后，会触发异常报错：TypeError: Cannot convert undefined or null to object。

[Demo.zip](https://github.com/user-attachments/files/17807534/Demo.zip)

### .NET Version

.Net 9.0

**Comment by ArgoZhang** [comment]
抱歉问题没有复现，可以尝试更新 `9.0.1` 版本试一下，项目模板页升级到了 `9.0.3` 使用 `dotnet new install Bootstrap.Blazor.Templates::*` 更新即可

https://github.com/user-attachments/assets/55939415-dd48-4b58-8cef-06deb912bc61

**Comment by LeiLei-Liu** [comment]
@ArgoZhang 很奇怪，我这边升级了9.0.1，重复测了几次，还是会报错，我再研究下。

![报错动画](https://github.com/user-attachments/assets/b8ee2d10-19db-4a4b-a4bd-3ad007b94abb)

**Comment by ArgoZhang** [comment]
@AeonsYu 最新版还有这个问题？

**Comment by LeiLei-Liu** [comment]
@AeonsYu 没找到解决方案，这个问题还在！

**Comment by ArgoZhang** [comment]
@LeiLei-Liu 你提供的那个复现例子已经好了啊，为什么问题还在？

**Comment by LeiLei-Liu** [comment]
![录屏](https://github.com/user-attachments/assets/2df66109-50ef-44bd-9f3b-c60ee931782f)
[BootstrapBlazorApp1.zip](https://github.com/user-attachments/files/18342077/BootstrapBlazorApp1.zip)

@ArgoZhang 之前提交的复现案例，您测试的时候未复现。这个是刚刚用最新的模板和最新的包生成的项目，问题还是在的。

**Comment by LeiLei-Liu** [comment]
![PixPin_2025-01-08_13-14-32](https://github.com/user-attachments/assets/62b5c5ad-a82a-4c97-9f91-315735eb1f3f)
 
@ArgoZhang 录屏上传错了

**Comment by ArgoZhang** [comment]
我这里还是没有这个错误。你能否清一下缓存，或开一个隐私模式试试看

**Comment by LeiLei-Liu** [comment]
@ArgoZhang 清缓存和隐私模式都试了下，还是会有这个错误。我不太会前端调试，简单定位了下报错的代码。

![Debug](https://github.com/user-attachments/assets/2ecf0f9c-c844-4181-aa16-bf55d3c5a2e7)

**Comment by nellyton** [comment]
我现在使用 **9.9.3** 版本（server模式），但是这个问题仍然存在。  
我大概找到了问题的初步复现情况：

我做了一个登录页，使用自定义的模板组件，内容如下：

```
@inherits LayoutComponentBase
<BootstrapBlazorRoot>
    <Layout UseTabSet="true">
        <Main>
            @Body
        </Main>
    </Layout>
</BootstrapBlazorRoot>
```
登录页面操作同上面一样，先什么都不填，验证不通过，再填内容，失焦 
这里的`UseTabSet`设为`false`，就会报这个错误： 
``` Uncaught TypeError: Cannot conversion undefined or null to object ```
如果设为`true`，就不会报错 
也就是说必须在标签内页使用验证才不会报错 
希望能修复一下

**Comment by ArgoZhang** [comment]
@nellyton 感谢参与讨论，帮忙右上角点一下 star 给我弄个复现工程，我研究一下。
