### ISSUE TITLE
IE 11的環境下使用Layout組件會報錯

### ISSUE THREAD

**Issue by NightSpark75** [dotnetcore/BootstrapBlazor#67]
會出現以下錯誤
Error: Microsoft.JSInterop.JSException: Could not find '$.bb_layout' ('$' was undefined).
在Chrome, Edge, FireFox測試過都正常
拿掉Layout組件後正常

**Comment by ArgoZhang** [comment]
wasm 模式吗？

**Comment by NightSpark75** [comment]
Blazor server

**Comment by ArgoZhang** [comment]
大佬可以加一下我的 QQ 群吗？795206915

**Comment by NightSpark75** [comment]
[2021-03-02T09:29:55.413Z] Error: Microsoft.JSInterop.JSException: Could not find '$.bb_layout' ('$' was undefined).
Error: Could not find '$.bb_layout' ('$' was undefined).
   at Anonymous function (https://localhost:44337/_framework/blazor.server.js:1:69862)
   at Anonymous function (https://localhost:44337/_framework/blazor.polyfill.min.js:1:4449)
   at Anonymous function (https://localhost:44337/_framework/blazor.polyfill.min.js:1:55749)
   at n.prototype.findFunction (https://localhost:44337/_framework/blazor.server.js:1:69796)
   at l (https://localhost:44337/_framework/blazor.server.js:1:69234)
   at Anonymous function (https://localhost:44337/_framework/blazor.server.js:1:71228)
   at B (https://localhost:44337/_framework/blazor.polyfill.min.js:1:89252)
   at n.jsCallDispatcher.beginInvokeJSFromDotNet (https://localhost:44337/_framework/blazor.server.js:1:71198)
   at Anonymous function (https://localhost:44337/_

**Comment by ArgoZhang** [comment]
polyfill 让ie 11 支持es6 加一个试试？
